### POST request to create a user : OK
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "name": "david",
  "email": "test@tes.com",
  "password": "azertyyy",
  "role": "admin"
}


### PUT request to update a user : OK
PUT http://localhost:3000/api/users/66dd91b4f4e2d505867da18a
Content-Type: application/json

{
  "name": "ben",
  "email": "test@tes.net",
  "password": "azertyyy"
}

### GET request to get all users : OK
GET http://localhost:3000/api/users
Content-Type: application/json

### POST request Token : OK
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "test@tes.com",
  "password": "azertyyy"
}

### POST request login user : OK
GET http://localhost:3000/api/users
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmRkOWEzODI2Nzc2ODUzOWZkOWRiMTIiLCJpYXQiOjE3MjU3OTg5NzcsImV4cCI6MTcyNjA1ODE3N30.PEszLoocMYCHFYBqye7QstBHB1y6HLqdMSa6muaELqY


### DELETE request to delete a user : OK
DELETE http://localhost:3000/api/users/66dd98c6de76f58ae739e52c
Content-Type: application/json


### POST request to create an article : OK
POST http://localhost:3000/api/articles
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmRkOWEzODI2Nzc2ODUzOWZkOWRiMTIiLCJpYXQiOjE3MjU3OTg5NzcsImV4cCI6MTcyNjA1ODE3N30.PEszLoocMYCHFYBqye7QstBHB1y6HLqdMSa6muaELqY

{
  "title": "New Article",
  "content": "Content of the new article",
  "state": "draft"
}

### GET request to get articles by user ID : OK
GET http://localhost:3000/api/users/66dd99630b48927c5ef95898/articles
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmRkOWEzODI2Nzc2ODUzOWZkOWRiMTIiLCJpYXQiOjE3MjU3OTg5NzcsImV4cCI6MTcyNjA1ODE3N30.PEszLoocMYCHFYBqye7QstBHB1y6HLqdMSa6muaELqY

### PUT request to update an article : OK
PUT http://localhost:3000/api/articles/66dd9a55267768539fd9db16
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmRkOTk2MzBiNDg5MjdjNWVmOTU4OTgiLCJpYXQiOjE3MjU3OTg3NjYsImV4cCI6MTcyNjA1Nzk2Nn0.vTyuO198msJ2Q2Zb1iWf-sgM3RCaTwy1cFRE4ibCJBk

{
  "title": "New Article",
  "content": "Content modifie of the new article",
  "state": "published"
}

### DELETE request to delete an article : OK
DELETE http://localhost:3000/api/articles/66dd9a55267768539fd9db16
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmRkOWEzODI2Nzc2ODUzOWZkOWRiMTIiLCJpYXQiOjE3MjU3OTg5NzcsImV4cCI6MTcyNjA1ODE3N30.PEszLoocMYCHFYBqye7QstBHB1y6HLqdMSa6muaELqY
Content-Type: application/json


//ana : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmRkOTk2MzBiNDg5MjdjNWVmOTU4OTgiLCJpYXQiOjE3MjU3OTg3NjYsImV4cCI6MTcyNjA1Nzk2Nn0.vTyuO198msJ2Q2Zb1iWf-sgM3RCaTwy1cFRE4ibCJBk