### POST request to create a user
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "name": "ana",
  "email": "test@tes.net",
  "password": "azertyyy",
    "role": "admin"
}


### PUT request to update a user
PUT http://localhost:3000/api/users/66cd8cd4d047dc73b449e0dc
Content-Type: application/json

{
  "name": "ben",
  "email": "test@tes.net",
  "password": "azertyyy"
}


### DELETE request to delete a user
DELETE http://localhost:3000/api/users/66cd8cd4d047dc73b449e0dc
Content-Type: application/json


### GET request to get all users
GET http://localhost:3000/api/users
Content-Type: application/json

### POST request Token
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "test@tes.net",
  "password": "azertyyy"
}

### POST request login user
GET http://localhost:3000/api/users
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY2Y2Q5MmNkZWRjMDQwNTk0NjU5YTRjMiIsIm5hbWUiOiJhbmEiLCJlbWFpbCI6InRlc3RAdGVzLm5ldCIsInJvbGUiOiJhZG1pbiIsImRhdGUiOiIyMDI0LTA4LTI3VDA4OjQ4OjEzLjMzNVoiLCJfX3YiOjB9LCJpYXQiOjE3MjQ3NDg1NDQsImV4cCI6MTcyNTAwNzc0NH0.CuZs2zAIqjRAgSfmvrEXvbpnRjAgoxkYl7aeA5jMC2Y


### POST request to create an article
POST http://localhost:3000/api/articles
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY2Y2Q5MmNkZWRjMDQwNTk0NjU5YTRjMiIsIm5hbWUiOiJhbmEiLCJlbWFpbCI6InRlc3RAdGVzLm5ldCIsInJvbGUiOiJhZG1pbiIsImRhdGUiOiIyMDI0LTA4LTI3VDA4OjQ4OjEzLjMzNVoiLCJfX3YiOjB9LCJpYXQiOjE3MjQ3NDg1NDQsImV4cCI6MTcyNTAwNzc0NH0.CuZs2zAIqjRAgSfmvrEXvbpnRjAgoxkYl7aeA5jMC2Y

{
  "title": "New Article",
  "content": "Content of the new article",
  "state": "draft"
}

### PUT request to update an article
PUT http://localhost:3000/api/articles/66cd90ec27d82048ad4259c3
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY2Y2Q5MmNkZWRjMDQwNTk0NjU5YTRjMiIsIm5hbWUiOiJhbmEiLCJlbWFpbCI6InRlc3RAdGVzLm5ldCIsInJvbGUiOiJhZG1pbiIsImRhdGUiOiIyMDI0LTA4LTI3VDA4OjQ4OjEzLjMzNVoiLCJfX3YiOjB9LCJpYXQiOjE3MjQ3NDg1NDQsImV4cCI6MTcyNTAwNzc0NH0.CuZs2zAIqjRAgSfmvrEXvbpnRjAgoxkYl7aeA5jMC2Y

{
  "title": "New Article",
  "content": "Content modified of the new article",
  "state": "published",
  "role": "admin"
}

### DELETE request to delete an article
DELETE http://localhost:3000/api/articles/66cd90ec27d82048ad4259c3
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY2Y2Q5MmNkZWRjMDQwNTk0NjU5YTRjMiIsIm5hbWUiOiJhbmEiLCJlbWFpbCI6InRlc3RAdGVzLm5ldCIsInJvbGUiOiJhZG1pbiIsImRhdGUiOiIyMDI0LTA4LTI3VDA4OjQ4OjEzLjMzNVoiLCJfX3YiOjB9LCJpYXQiOjE3MjQ3NDg1NDQsImV4cCI6MTcyNTAwNzc0NH0.CuZs2zAIqjRAgSfmvrEXvbpnRjAgoxkYl7aeA5jMC2Y
Content-Type: application/json


